# Generated by Django 3.2.9 on 2022-03-14 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ventas', '0002_pedidoitem_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_personalizado',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pedido_personalizado',
            name='fecha_cita',
        ),
        migrations.RemoveField(
            model_name='pedido_personalizado',
            name='total_pagar',
        ),
        migrations.AddField(
            model_name='pedido_personalizado',
            name='cantidad',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='pedido_personalizado',
            name='pedido_id',
            field=models.ForeignKey(db_column='pedido_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ventas.pedido', verbose_name='Id del Pedido'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente_id',
            field=models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='empleado_id',
            field=models.ForeignKey(blank=True, db_column='empleado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pedido_personalizado',
            name='servicio_id',
        ),
        migrations.AddField(
            model_name='pedido_personalizado',
            name='servicio_id',
            field=models.ForeignKey(db_column='servicio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ventas.servicio', verbose_name='Id del Servicio'),
        ),
        migrations.RemoveField(
            model_name='pedido_personalizado',
            name='servicio_personalizado_id',
        ),
        migrations.AddField(
            model_name='pedido_personalizado',
            name='servicio_personalizado_id',
            field=models.ForeignKey(db_column='servicio_personalizado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ventas.servicio_personalizado', verbose_name='Servicios Personalizados'),
        ),
    ]
