# Generated by Django 3.2.9 on 2022-03-14 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ventas', '0003_auto_20220313_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('cita_id', models.ForeignKey(db_column='cita_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ventas.cita')),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_calendario_id', to=settings.AUTH_USER_MODEL)),
                ('empleado_id', models.ForeignKey(db_column='empleado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado_calendario_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
