# Generated by Django 3.2.9 on 2022-03-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_calendario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'verbose_name': 'calendario', 'verbose_name_plural': 'calendario'},
        ),
        migrations.AlterModelTable(
            name='calendario',
            table='calendario',
        ),
    ]
