# Generated by Django 3.2.9 on 2022-03-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_auto_20220313_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio_personalizado',
            name='duracion',
            field=models.PositiveIntegerField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
