# Generated by Django 3.2.9 on 2022-03-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0006_auto_20220313_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='esPersonalizado',
            field=models.BooleanField(default=False, verbose_name='Es personalizado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='servicio_personalizado',
            name='duracion',
            field=models.PositiveIntegerField(),
        ),
    ]
