# Generated by Django 3.2.9 on 2022-03-24 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0007_auto_20220323_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='transaccion_id',
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='servicio_personalizado_id',
            field=models.ForeignKey(db_column='servicio_personalizado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ventas.servicio_personalizado', verbose_name='Servicios Personalizados'),
        ),
    ]
