# Generated by Django 3.2.9 on 2022-03-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0008_auto_20220323_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_personalizado',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
