# Generated by Django 3.2.8 on 2022-03-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambios',
            name='Sangria_Letra',
        ),
        migrations.AddField(
            model_name='cambios',
            name='Texto_Mision',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cambios',
            name='Texto_Vision',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
