# Generated by Django 3.2.8 on 2022-03-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0002_auto_20220319_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cambios',
            old_name='tamano_letra',
            new_name='tamano_Titulo',
        ),
        migrations.AddField(
            model_name='cambios',
            name='tamano_Texto',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
