# Generated by Django 3.2.9 on 2022-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0003_auto_20220319_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='cambiosFooter',
            fields=[
                ('id_footer', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Direccion', models.CharField(max_length=500)),
                ('Telefono', models.CharField(max_length=20)),
                ('Derechos', models.CharField(max_length=20)),
                ('Footer_Color_Letra', models.CharField(max_length=20)),
                ('Footer_Color_Fondo', models.CharField(max_length=20)),
                ('Footer_tamano_Titulo', models.CharField(max_length=20)),
                ('Footer_tamano_Texto', models.CharField(max_length=20)),
                ('Footer_Tipo_Letra', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'footer',
            },
        ),
    ]
